### ISSUE TITLE
Can I change themes while priiloader is installed on vWii?

### ISSUE THREAD

**Issue by Vinnievovi** [Naim2000/directory#1]
I would like to know if I installed priiloader on vWii and change the theme while it is installed, will it brick?  I created 2 themes for vWii, one is the black theme, and the other theme is the default white one.  I can install them without problems with mymenuify on vWii.

**Comment by Naim2000** [comment]
It won't brick, the app manually finds the asset archive. If the theme itself causes a brick then you have priiloader. (You also have vWii decaffeinator.)
